### ISSUE TITLE
Hyper Theme

### ISSUE THREAD

**Issue by cevr** [GulajavaMinistudio/Mayukai-Theme#1]
Hi There!

Thanks a lot for working on this theme, it's great.

I made a theme for [Hyper](https://github.com/zeit/hyper) based off of Mirage Darker.

[Here's the link!](https://github.com/cevr/hyper-mayukai)

**Comment by GulajavaMinistudio** [comment]
Wow, thank you for creating Mayukai Hyper Theme . Can i add and  reference it in Mayukai Theme Readme file ?

**Comment by cevr** [comment]
@GulajavaMinistudio Yes, please! Thank you for making the theme 🥇

**Comment by GulajavaMinistudio** [comment]
Closed after updating Readme File
