### ISSUE TITLE
Colourblind safe scheme

### ISSUE THREAD

**Issue by andyprasetya** [GulajavaMinistudio/Mayukai-Theme#14]
Please provide, at least, a scheme for colourblind safe. Ref: https://colorbrewer2.org/

**Comment by GulajavaMinistudio** [comment]
Thanks for feedback and reference. 
Currently we don't have a plan for adding this color blind safe scheme in our current scheme of theming. But we'll experiment it in future.

And as for now, here's some reference for color theme that support color blind safe. We also have an option for color scheme that looks like  Dracula theme, named Mayukai Alucard.
https://colorblind-themes.tech/

**Comment by andyprasetya** [comment]
Thank you for your attention, and I'll look for your suggestion. Anyway, this theme is an awesome work. Just keep on moving!
