### ISSUE TITLE
Several terminal themes

### ISSUE THREAD

**Issue by elianiva** [GulajavaMinistudio/Mayukai-Theme#2]
Hi! Thank you for this awesome theme. I made several terminal theme based on Mayukai Mirage.

Currently it's available as `.Xresources` for terminal that uses it as its colours configuration. It's also available for Kitty and Alacritty terminal.

[They're here](https://github.com/irrellia/mayukai-terminal-themes)

Thank you!

**Comment by GulajavaMinistudio** [comment]
Thank you for your contribution :smile: 

This is for Linux Terminal , right ? for Arch based distro, or for all Linux distro can use this Terminal Theme ?

[https://wiki.archlinux.org/index.php/X_resources](https://wiki.archlinux.org/index.php/X_resources)

**Comment by GulajavaMinistudio** [comment]
Added to Readme file for this Terminal Theme.
