### ISSUE TITLE
add tokens for messages

### ISSUE THREAD

**Issue by jshinonome** [GulajavaMinistudio/Mayukai-Theme#20]
I like the color in this theme, great work!!

I notice there is message.error, which is red.
Can you please add tokens for message.info(green), message.warn(orange)?

```
        {
            "scope": [
                "message.error"
            ],
            "settings": {
                "foreground": "#ff3333"
            }
        },
```

**Comment by GulajavaMinistudio** [comment]
I think i can work with that. 
Any docs for additional scope 
message.info and message.warn ?

**Comment by jshinonome** [comment]
Thank you. I am also thinking of
- comment.line.attention(dark red)
- comment.line.todo(dark orange)
So I can use those to highlight comment.

**Comment by GulajavaMinistudio** [comment]
For comment.line , I'm not sure about applying that, because after checking in VS Code token color API, there is none of them available. 

https://code.visualstudio.com/api/references/theme-color

**Comment by GulajavaMinistudio** [comment]
After checking my syntax token with VS Code API, i have implemented it before, with this token : 

editorError.foreground: Foreground color of error squiggles in the editor.
editorWarning.foreground: Foreground color of warning squiggles in the editor.

Maybe you can check it.
https://code.visualstudio.com/api/references/theme-color#editor-colors

But for 
editorInfo.foreground , i'm not implemented it and apply with default transparent color.

**Comment by jshinonome** [comment]
Those that I asked will be used as q language tokens in my vscode plugin for q. Understood if you don't want to add them, I can add them manullay.

**Comment by jshinonome** [comment]
Just let you know it looks like, but no worries about applying them.
![image](https://user-images.githubusercontent.com/64458591/106348620-ddfb7880-630a-11eb-875d-ad5624205744.png)

**Comment by GulajavaMinistudio** [comment]
I think it work like "Better Comments" extension. This is available in vs code too. Maybe you should check this out ? 
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

I'm not gonna apply that, since this extension theme is not specific language and can run on any language plugin service.

**Comment by jshinonome** [comment]
Thanks anyway, feel free to close it. I will probably make a theme later.

**Comment by GulajavaMinistudio** [comment]
Thank you for contacting us about this discussion
