### ISSUE TITLE
[Request] (Neo) VIM Port

### ISSUE THREAD

**Issue by ricbermo** [GulajavaMinistudio/Mayukai-Theme#37]
Hello.

Thanks for taking your time to put together this masterpiece. I'd kindly ask if it'd be possible to do some kind of port to Neovim/Vim. I'm using this theme on vscodium, kitty and I'd love to use it on my neovim setup as well.

Thanks so much

**Comment by GulajavaMinistudio** [comment]
> Hello.
> 
> Thanks for taking your time to put together this masterpiece. I'd kindly ask if it'd be possible to do some kind of port to Neovim/Vim. I'm using this theme on vscodium, kitty and I'd love to use it on my neovim setup as well.
> 
> Thanks so much

Thank you for using Mayukai Theme in your VS Code.  Unfortunately, until now we're focusing on VS Code and VS Codium build.  No plan for supporting other editor such as Sublime, Vim, and Jetbrains IDE. 

But we're providing our color swatch for other contributor or theme creator to use same color swatch as ours. You can check color hex code in here in "themes" folder.
[https://github.com/GulajavaMinistudio/Mayukai-Theme/tree/master/themes](https://github.com/GulajavaMinistudio/Mayukai-Theme/tree/master/themes)

**Comment by ricbermo** [comment]
TY, I'm closing this issue.
