### ISSUE TITLE
Different color for local variables

### ISSUE THREAD

**Issue by enkeyz** [GulajavaMinistudio/Mayukai-Theme#40]
Would be nice to get a different color for variables, that local to a function, like in Dark+.

Dark+:
(`results`, `resultChannel`, `url`, `i` and `r` variables are local to CheckWebsites function)
![image](https://user-images.githubusercontent.com/17646853/165085892-379871be-78da-47a9-bb85-6e2a04452684.png)

Mayukai Semantic Mirage:
![image](https://user-images.githubusercontent.com/17646853/165086039-6d58925c-29e8-4cf3-9b89-298ea4818d0b.png)

**Comment by GulajavaMinistudio** [comment]
Good suggestion. Can you paste your code example in this issue with markdown highlight ?
So i can try and figure it with your code.

**Comment by enkeyz** [comment]
Sure, there you go:

```go
package main

type WebsiteChecker func(string) bool

type result struct {
	string
	bool
}

func CheckWebsites(wc WebsiteChecker, urls []string) map[string]bool {
	results := make(map[string]bool)
	resultChannel := make(chan result)

	for _, url := range urls {
		go func(url string) {
			resultChannel <- result{url, wc(url)}
		}(url)
	}

	for i := 0; i < len(urls); i++ {
		r := <-resultChannel
		results[r.string] = r.bool
	}

	return results
}
```

**Comment by GulajavaMinistudio** [comment]
@enkeyz  I try to implemented only on Mayukai Semantic Mirage, and scoped for Go language.
![Screenshot_2022-05-03_15-41-44](https://user-images.githubusercontent.com/11639412/166427087-e38a0f9d-4a4c-4a7f-a465-2a2c6a2afcda.png)

And it use color scheme that suitable with Mayukai Semantic Mirage **#D4BFFF**

This color for variable will available on next update.

**Comment by enkeyz** [comment]
Tyvm <3

**Comment by enkeyz** [comment]
@GulajavaMinistudio I just got the update, but other then in the Mayukai Semantic Mirage theme, there's no different color for local variables:

Mayukai Dark:
![image](https://user-images.githubusercontent.com/17646853/166487150-d498caa3-b7fa-4ba1-b5de-66e749aa1975.png)

**Comment by GulajavaMinistudio** [comment]
I see, can you paste your snippet code again in markdown on next comment ? so we can try it again ?
We just implemented on semantic mirage first. But on other color scheme theme, such as Mayukai Mono, Midnight, Alucard, and Sunset, we are not implemented it. Because it can  break other people preference on how variable should coloring.

Maybe on next update , we will try to implemented it on mayukai dark.

**Comment by GulajavaMinistudio** [comment]
@enkeyz Hello Enkeys, you can add your custom property on current theme you're using, with this simple VS Code settings.

![Screenshot_2022-05-04_04-32-19](https://user-images.githubusercontent.com/11639412/166570087-0d5dfa91-9e6a-4959-bf4f-c0fc9305391b.png)

Open your VS Code Settings, and 

```    
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "name": "Variable Property for Go",
                "scope": [
                    "variable.other.assignment.go"
                ],
                "settings": {
                    "foreground": "#d4bfff"
                }
            },
        ]
    }
```

And there is a good explanation on Stackoverflow about how to custom other theme with VS Code Settings. 
[Token Color Customization with Textmate Scopes](https://stackoverflow.com/questions/68704584/vs-code-change-color-of-variables)

[Semantic Token Color Customization](https://medium.com/@danromans/how-to-customize-semantic-token-colorization-with-visual-studio-code-ac3eab96141b)

**Comment by GulajavaMinistudio** [comment]
I'm adding this docs to Issue, and maybe can help you
[[DOC] How to customize color on variable, function, and other token coloring](https://github.com/GulajavaMinistudio/Mayukai-Theme/issues/43)

**Comment by GulajavaMinistudio** [comment]
I'm adding this docs to Issue, and maybe can help you
[[DOC] How to customize color on variable, function, and other token coloring](https://github.com/GulajavaMinistudio/Mayukai-Theme/issues/43)
