### ISSUE TITLE
Current line highlight's color could use some contrast

### ISSUE THREAD

**Issue by enkeyz** [GulajavaMinistudio/Mayukai-Theme#41]
As you can see, it's barely visible:
![image](https://user-images.githubusercontent.com/17646853/165725917-187b32c2-85db-4d38-a472-c1a6f1c6f406.png)

Ayu Dark:
![image](https://user-images.githubusercontent.com/17646853/165726087-5c86d48b-1921-47fa-af2f-4b48cad207da.png)

**Comment by GulajavaMinistudio** [comment]
Thank you for suggestion. We have added it in every color scheme in Mayukai Theme, and available on next update. You can see it on screenshot above.
![Screenshot_2022-05-03_15-55-05](https://user-images.githubusercontent.com/11639412/166427579-8bf40e5f-cf32-4636-a0d0-f1b038b1e6af.png)

**Comment by enkeyz** [comment]
@GulajavaMinistudio you're awesome!
