### ISSUE TITLE
Fix contrast menu item

### ISSUE THREAD

**Issue by pexid** [GulajavaMinistudio/Mayukai-Theme#46]
Saya berharap, ada pembaharuan terbaru untuk memperbaiki warna kontras pada menu popup. Saya rasa itu akan menjadi lebih baik. Terimaskasih! 😊

**Comment by GulajavaMinistudio** [comment]
Terima kasih sarannya, ini menu pop up di bagian yang mana kah ? boleh sertakan screenshot nya di issue ini. Terima kasih.

> Saya berharap, ada pembaharuan terbaru untuk memperbaiki warna kontras pada menu popup. Saya rasa itu akan menjadi lebih baik. Terimaskasih! 😊
