### ISSUE TITLE
Font Ligatures

### ISSUE THREAD

**Issue by lem0nify** [GulajavaMinistudio/Mayukai-Theme#9]
Theme conflicts with some font ligatures in VSCode.
I use [JetBrains Mono](https://www.jetbrains.com/lp/mono/) and font ligatures are turned on in VSCode settings:
```JSON
"editor.fontLigatures": true,
```
But some ligatures like `->` or `<>` don't work because symbols have different coloring:
![image](https://user-images.githubusercontent.com/17163615/77270681-acaf2680-6cbd-11ea-8282-a3d67d5f1902.png)

**Comment by GulajavaMinistudio** [comment]
Thank you for reporting issue. 
Have you try to disable "Semantic highlighting" in VS Code Settings?

I testing with ligature font, and it work well. 
![code](https://user-images.githubusercontent.com/11639412/77284569-97f48200-6d01-11ea-9699-704519070728.png)

**Comment by lem0nify** [comment]
@GulajavaMinistudio Yes, Semantic Hightlighting is turned off but I found out that it differs from language to language. I made my screenshot with F# highlighting (Ionide).

**Comment by GulajavaMinistudio** [comment]
I'm testing with F# language now. And the results is work well with yellow coloring in ligature. Like this picture below.
![Screenshot_2020-03-25_09-16-28](https://user-images.githubusercontent.com/11639412/77494905-aebde480-6e79-11ea-951e-1279762fdc73.png)

Can you provide us with some detail, such as Editor token scopes ? First, press Ctrl + Shift + P . And then write Inspect Editor Tokens and Scopes in Command Palette. Select this, and move your cursor to desired syntax with weird coloring.
 
![Screenshot_2020-03-25_09-18-06](https://user-images.githubusercontent.com/11639412/77494979-e62c9100-6e79-11ea-99de-1eb0e444e0c6.png)

And the result will show us with this . Pop up with the detail of Textmate scopes involved.
![Screenshot_2020-03-25_09-17-25](https://user-images.githubusercontent.com/11639412/77495051-1411d580-6e7a-11ea-8d95-3af0b701927d.png)

Or you can try send us some code snippets that involved with those problems, and let me check it. 

================

Or have you try with different font other than Jetbrains Mono ? Such as Fira Code or Iosevka Font ? And the problems still persist ?

**Comment by GulajavaMinistudio** [comment]
Mark it as closed, as there is no further response.
